#!/bin/sh
set -e

echo 'copy WordLooper.app to Devive Application folder'

TARGET_COPIED_NAME='WordLooper.app'
RESOURCES_TO_COPY_PATH=$BUILT_PRODUCTS_DIR/$TARGET_COPIED_NAME
TARGET_SOURCE_PATH='/Applications/'

rm -r $TARGET_SOURCE_PATH$TARGET_COPIED_NAME

echo $RESOURCES_TO_COPY_PATH
echo $TARGET_SOURCE_PATH

mkdir -p $TARGET_SOURCE_PATH

cp -R  $RESOURCES_TO_COPY_PATH $TARGET_SOURCE_PATH
